# Copyright 2022 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

project_name: toml-merge

changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^build:'

release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/jimmidyson/toml-merge/compare/{{ .PreviousTag }}...{{ .Tag }}

builds:
  - id: toml-merge
    dir: ./cmd/toml-merge
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.commitDate={{ .CommitDate }}'
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.gitCommit={{ .FullCommit }}'
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.gitTreeState={{ .Env.GIT_TREE_STATE }}'
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.gitVersion=v{{ trimprefix .Version "v" }}'
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.major={{ .Major }}'
      - -X 'github.com/jimmidyson/dkp-cli-runtime/core/cmd/version.minor={{ .Minor }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
  # This is a hack documented in https://github.com/goreleaser/goreleaser/blob/df0216d5855e9283d2106fb5acdb0e7b528a56e8/www/docs/customization/archive.md#packaging-only-the-binaries
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - toml-merge
dockers:
  - image_templates:
      # Specify the image tag including `-amd64` suffix if the build is not a snapshot build or is not being built on
      # arm64 machine. This allows for using the snapshot image build without the archtecture specific suffix
      # consistently on local machines, i.e. can always use `jimmidyson/toml-merge:v<VERSION>` on the machine the snapshot
      # is built on.
      #
      # For a release build the `-amd64` suffix will always be included and the `docker_manifests` specification below
      # will create the final multiplatform manifest to be pushed to the registry.
      - 'jimmidyson/toml-merge:v{{trimprefix .Version "v"}}{{ if or (not .IsSnapshot) (not (eq .Runtime.Goarch "amd64")) }}-amd64{{ end }}'
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=toml-merge"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - image_templates:
      # Specify the image tag including `-amd64v8` suffix if the build is not a snapshot build or is not being built on
      # arm64 machine. This allows for using the snapshot image build without the archtecture specific suffix
      # consistently on local machines, i.e. can always use `jimmidyson/toml-merge:v<VERSION>` on the machine the snapshot
      # is built on.
      #
      # For a release build the `-amd64v8` suffix will always be included and the `docker_manifests` specification below
      # will create the final multiplatform manifest to be pushed to the registry.
    - 'jimmidyson/toml-merge:v{{trimprefix .Version "v"}}{{ if or (not .IsSnapshot) (not (eq .Runtime.Goarch "arm64")) }}-arm64v8{{ end }}'
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=toml-merge"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
docker_manifests:
  - name_template: jimmidyson/toml-merge:v{{trimprefix .Version "v"}}
    image_templates:
    - jimmidyson/toml-merge:v{{trimprefix .Version "v"}}-amd64
    - jimmidyson/toml-merge:v{{trimprefix .Version "v"}}-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incminor .Tag }}-dev"
